export enum Card11KeyEnum {
  Lang = 'lang',
  Sell = 'sell',
  Coin = 'coin',
  Fee = 'fee',
  FeeBox = 'feebox',
  Factor = 'factor',
  Pnl = 'pnl',
  Pnl2 = 'pnl2',
  Background = 'background',
  AvgEntryPrice = 'fair-price',
  AvgClosePrice = 'entry-price',
  Time = 'time',
  // OpenTime = 'time',
  // CloseTime = 'close_time',
  Referral = 'referral',
  Qr = 'qr',
  AvgEntryPriceTitile = 'fair-pricet',
  AvgClosePriceTitile = 'entry-pricet',
  TimeTitile = 'timet',
  // OpenTimeTitile = 'timet',
  // CloseTimeTitile = 'close_timet',
}
